
services:
  
  elasticsearch:
    image: elasticsearch:8.17.1
    environment:
      - discovery.type=single-node
      - ELASTIC_PASSWORD=changeme # username is: elastic
      - ES_JAVA_OPTS=-Xms512m -Xmx512m # Set the JVM heap size: https://www.elastic.co/guide/en/elasticsearch/reference/current/advanced-configuration.html#set-jvm-heap-size
    ports:
      - "9200:9200"
    networks:
      - elk-network

  kibana:
    image: kibana:8.17.1
    ports:
      - "5601:5601"
    networks:
      - elk-network
    
  # TODO: add logstash

networks:
  elk-network:
    driver: bridge